apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          imagePullPolicy: IfNotPresent
          image: rabbitmq:3-management
          ports:
            - containerPort: 15672
      
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: NodePort
  ports:
    - port: 15672
      targetPort: 15672
  selector:
    app: rabbitmq